### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by vfarcic** [thomasjpfan/docker-scaler#2]
I think that the project should be capable of sending notifications both when scaling was successful,  when it failed, and when it did nothing because the service is already scaled to min or max.

I don't think that implementing all different notifications (e.g. email, Slack, etc) would be a good idea. Instead, I'd let the project send a request to a configurable address. One use case would be to send a notification about scaling status to AlertManager. We can start with a simple request and refine it later on. It could be an equivalent of:

```
curl -H "Content-Type: application/json" \
    -d '[{"labels":{"alertname":"scaler", "service":"my-service", "delta":"1", "status":"success", "message":"Scaled from 3 to 4 replicas"}}]' \
    "http://[ALERT_MANAGER_DNS]:[ALERT_MANAGER_PORT]/api/v1/alerts"
```

I haven't tried the format of the JSON so it might need some refining to make it AlertManager-friendly. From there on, it should be trivial to configure AM to process all alerts named `scaler` to forward notifications to Slack, email, or somewhere else.

What do you think?

**Comment by thomasjpfan** [comment]
Sending an alert back to the Alertmanager looks good. 

Reviewing the spec for posting an alert in the docs: https://prometheus.io/docs/alerting/notifications/, or the source: https://github.com/prometheus/common/blob/master/model/alert.go, it looks like `generatorURL` is a mandatory field. At a glance, it doesn't seem like alertmanager checks that this is actually a URL, so it can be any string. If there isn't anything we can always use an empty string.

`alertname`, `status`, and `service` would be good labels.  I would put `delta` and `message into an annotation. All together the POST request will have the following body:

```json
[{
   "labels": {
      "alertname": "scaler",
      "service": "my-service",
      "status": "success"
   },
   "annotations": {
      "message": "Scaled from 3 to 4 replicas",
      "delta": "1"
   },
   "generatorURL": ""
}]
```

If we leave out `startsAt` and `endsAt`, the alertmanager will resolve in 5 minutes: https://github.com/prometheus/alertmanager/blob/a566036015c0cfd1bf218b5de922e57cfa623999/config/config.go#L298.

I'll write up the client to send notifications. The specifics of the POST request can change depending on what we need.

**Comment by thomasjpfan** [comment]
I added notifications to Alertmanager (with unit/integration tests). In summary, the post body looks like following:
```json
[{
   "labels": {
      "alertname": "scaler",
      "service": "my-service",
      "status": "success"
   },
   "annotations": {
      "summary": "Scaled from 3 to 4 replicas",
      "request": "Scale service: example_web, delta: 1"
   },
   "generatorURL": ""
}]
```
I also updated the README to demonstrate how to test out this functionality. After issuing a POST request for scaling, you can use [amtool](https://github.com/prometheus/alertmanager) to check that Alertmanager has received the alert.

**Comment by vfarcic** [comment]
Can you ping me on HangOuts (user: viktor@farcic.com) or Skype (user: vfarcic)? I have a few ideas I'd like to discuss and I'm not sure I have your email.
