### ISSUE TITLE
Scaling to 0 removes alert configurations

### ISSUE THREAD

**Issue by patrickleet** [thomasjpfan/docker-scaler#9]
See https://github.com/vfarcic/docker-flow-monitor/issues/35 for more details.

Not sure if this could be solved from docker-scaler side somehow?

**Comment by vfarcic** [comment]
I can add the option to DFSL that would disable sending "remove" notifications when a service is scaled to 0 replicas. if that would work for you, please open an issue in DFSL.

**Comment by thomasjpfan** [comment]
Feature is available in DFM: [release 18.02.21-52](https://github.com/vfarcic/docker-flow-monitor/releases/tag/18.02.21-52).
